Numpy program to create an array of all even integers between 30 and 70

In [ ]:
import numpy as np

In [4]:
even_integers = np.arange(32, 70, 2)
print(even_integers)

[32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [7]:
even_integers_alternate = np.linspace(32, 68, 19, dtype=int)
print(even_integers_alternate)

[32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [8]:
even_integers = np.fromfunction(lambda x: 32 + 2 * x, (19,), dtype=int)
print(even_integers)

[32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [9]:
even_integers_method4 = np.array([i for i in range(32, 70, 2)])
print(even_integers_method4)

[32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [11]:
even_integers_method4 = np.array([i for i in range(32, 70) if i % 2 == 0])
print(even_integers_method4)

[32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]
