Numpy

In [3]:
import numpy as np

In [24]:
arr=np.array([1,2,3,4,5])

In [29]:
print("sum:\n",np.sum(arr))
print("min:\n",np.min(arr))
print("max:\n",np.max(arr))
print("argmax:\n",np.argmax(arr))
print("argmin:\n",np.argmin(arr))
print("mean:\n",np.mean(arr))

sum:
 15
min:
 1
max:
 5
argmax:
 4
argmin:
 0
mean:
 3.0


In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=np.transpose(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
c = np.matmul(a, b)
print(c)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [9]:
d=c**2
print(d)

[[  196  1024  2500]
 [ 1024  5929 14884]
 [ 2500 14884 37636]]


In [19]:
print("a:\n",a)
print("b:\n",b)
print("a+1:\n",a+1)
print("a+b:\n",a+b)
print("a-b:\n",a-b)
print("a*b:\n",a*b)
print("a/b:\n",a/b)

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
a+1:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
a+b:
 [[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
a-b:
 [[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
a*b:
 [[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
a/b:
 [[1.         0.5        0.42857143]
 [2.         1.         0.75      ]
 [2.33333333 1.33333333 1.        ]]
